### ISSUE TITLE
Duplicate columns in optimization_data.trusted_advisor_data

### ISSUE THREAD

**Issue by gmg105** [awslabs/cid-framework#108]
After running the step function to generate a new trusted_advisor_data dataset, the resulting table in Athena cannot be queried due to the following duplicate columns:

instance id
connection id 
gateway id
hosted zone id

The template used in CF CID Data Collection was v3.0.3.

**Comment by jesperalmstrom** [comment]
Just finished the workshop v 3.0.6 and got the same issue.

**Comment by yprikhodko** [comment]
Sorry you've hit this issue. We're working on the fix in new version. 
However if you deploy TAO dashboard (https://catalog.workshops.aws/awscid/en-US/dashboards/advanced/trusted-advisor/deployment#option-2:-automation-scripts-deployment) you will get new Athena table ta_organizational_view_reports  created which doesn't have issue with duplicates.

**Comment by jesperalmstrom** [comment]
For some reason, new duplicates have occurred after the Glue Crawler have been running a couple of times.

**Comment by esc1144** [comment]
That is possible since each TA check has its own little schema of detailed information and not all checks come in at one time. Glue then updates the table over subsequent runs.

**Comment by iakov-aws** [comment]
@jesperalmstrom does this works correctly with TAO dashboard as Yuriy suggested here https://github.com/awslabs/cid-framework/issues/108#issuecomment-2071105070 ?

**Comment by jesperalmstrom** [comment]
Just deployed it and replaced my data sets in my dashboards.

**Comment by awssteph** [comment]
Hey, having the same issue, @jesperalmstrom what do you mean you replaced the data set? Could you say which way round?

**Comment by VoicuAWS** [comment]
Still working on this folks, I am hoping to have some results soon.

**Comment by iakov-aws** [comment]
Fixed in 3.0.10 thanks @VoicuAWS !
