### ISSUE TITLE
costfilters not populating in budgets data

### ISSUE THREAD

**Issue by joegajeckyj** [awslabs/cid-framework#124]
Hi,

I have been trying to join the budgets data to my CID and the lambda is not pulling the filters so I can join to the cost allocation tags

I have worked around by updating the lambda as follows

https://github.com/awslabs/cid-framework/blob/6b44902f027bd3d9f96b47c082db8c15ce22e6eb/data-collection/deploy/module-budgets.yaml#L160C16-L175C37

to this         

if 'CostFilters' not in budget or len(budget['CostFilters']) == 0:

**Comment by marcodb-aws** [comment]
hello!

we're updating the budget integration of CID thanks to AWS Budget Tags new feature.
This should solve your problem with match between AWS Budget and Cost Allocation tag.

Thank you for your interest and patience, 
I'll post relevant update here.

Thanks!

**Comment by iakov-aws** [comment]
Tagging feature was released. Now you can use tags from Budgets directly 🚀
