### ISSUE TITLE
10000s of rogue tables (Cost Optimization Hub Detail)

### ISSUE THREAD

**Issue by joegajeckyj** [awslabs/cid-framework#125]
Hi,

I have deployed the latest version on 2 separate AWS Orgs and I'm seeing the same issue for the Cost Optimization Hub Module

The crawler is creating 10000s of tables all with what I can only describe as ids, this has caused our Quicksight to time out trying to load the tables and views in the cost_optimization database i had to disable the module as it was reaching 40000 tables

For example 
![image](https://github.com/awslabs/cid-framework/assets/23356701/ed0b2349-d979-48ff-b77c-87ed3adbc1c9)
![image](https://github.com/awslabs/cid-framework/assets/23356701/97ab21fc-f3dc-4fbd-943b-bf846ec8189b)

**Comment by esc1144** [comment]
Hi joegajeckyj,
That is definitely a problem and I am sorry you have encountered it. Can you tell me if you were running the module previously and did a recent update through CloudFormation when this started? Please provide the version of the framework that you have deployed. Also, do you have an Enterprise Support contract and a TAM? 

In the meantime, I have seen this before and created a script to help people delete the tables. Edit the database and S3 path variables as needed

```
#!/bin/bash

DATABASE="optimization_data"
S3_PATH_FILTER="s3://cid-data-[your account number]/cost-optimization-hub/*"

# Get list of tables in database
TABLES=$(aws glue get-tables --database-name $DATABASE --query "TableList[*].Name" --output text)

# Loop through tables and check S3 location
for TABLE in $TABLES; do

  # Get table metadata
  LOCATION=$(aws glue get-table --database-name $DATABASE --name $TABLE --query "Table.StorageDescriptor.Location" --output text)

  # Check if location matches wildcard path
  if [[ $LOCATION == $S3_PATH_FILTER ]]; then
    # Delete table
    aws glue delete-table --database-name $DATABASE --name $TABLE
  fi
done
```

**Comment by joegajeckyj** [comment]
Hi, thanks for the response, and the script, i had fashioned myself one but this looks more comprehensive
I will share on email our TAM and also I have e support ticket open for this issue.

**Comment by joegajeckyj** [comment]
Yes I did the update through CFN and its currently running 
Description: CID Data Collection Stack v3.0.6

**Comment by esc1144** [comment]
Cool and thanks for the quick reply. Yes, it would be easier to work with your TAM and then we can get on a call, if needed. We had issues with the variability in the CO Hub detail record structures and it was tripping up Glue over time. So we made a change in a recent version to coerce the schema and that seems to work fine except that if you have previous tables, it causes this issue you saw. In the other case where this happened, once all the tables for that module were deleted (including the original) and then the module or Crawler executed again, it all lined up properly into the single detail table. 

FYI, I originally created this script by prompting Amazon Q via CodeWhisperer and only had to make a slight tweak.

**Comment by esc1144** [comment]
Okay, I reached out to your TAM and we can coordinate that way. The provided script will target all of the Cost Optimization Hub tables. We need to remove all of those uuid named tables at a minimum and I think it best to remove the code detail one as well. All of your data for those will still be in S3 and we then need the crawler to rebuild the table from that. What we may also need to do is remove the S3 files for the Hub data from prior to your recent upgrade to the framework. We can walk through it together on a call with your TAM, if you prefer.

**Comment by joegajeckyj** [comment]
Hi,

Yes please that would be good.  Ill reach out to him also.

Joe
________________________________

**Comment by esc1144** [comment]
Ahead of a session with your TAM, one thing you can do now is update the crawler definition and set the max table threshold to 1 [1]. Make sure it is the crawler for the CO Hub Detail and not Summary. We will also ultimately incorporate that into the code. 

[1] https://docs.aws.amazon.com/glue/latest/dg/crawler-configuration.html#crawler-maximum-number-of-tables
