### ISSUE TITLE
When are templates synced to aws-well-architected-labs bucket?

### ISSUE THREAD

**Issue by lvthillo** [awslabs/cid-framework#129]
When you follow the tutorial [here](https://catalog.workshops.aws/awscid/en-US/dashboards/foundational/cudos-cid-kpi/deploy), templates from the following bucket is used: aws-well-architected-labs, e.g.:
https://aws-well-architected-labs.s3.amazonaws.com/Cost/Labs/300_Optimization_Data_Collection/account-collector.yaml

The Lambda here still uses Python 3.8 while it has already been upgraded to Python 3.10 in this repository.
https://github.com/awslabs/cid-framework/blob/main/data-collection/deploy/account-collector.yaml#L85

Same for https://github.com/awslabs/cid-framework/blob/main/data-collection/deploy/module-trusted-advisor.yaml#L101 and https://aws-well-architected-labs.s3.amazonaws.com/Cost/Labs/300_Optimization_Data_Collection/module-trusted-advisor.yaml

**Comment by iakov-aws** [comment]
These bukets are no longer updated. Please update data collection to the v3 https://catalog.workshops.aws/awscid/en-US/data-collection/update#update-from-legacy-versions
