### ISSUE TITLE
License Manager module does not deploy

### ISSUE THREAD

**Issue by cmogeni** [awslabs/cid-framework#150]
The license manager module template is missing from the bucket aws-managed-cost-intelligence-dashboards. The s3 file path that's expected is s3://aws-managed-cost-intelligence-dashboards/cfn/data-collection/module-license-manager.yaml

**Comment by iakov-aws** [comment]
it is not released yet! hold on!

**Comment by iakov-aws** [comment]
it is now

please retry update / deployment.
https://github.com/awslabs/cid-framework/releases/tag/3.0.10

**Comment by cmogeni** [comment]
Thank you, looks good
