### ISSUE TITLE
Use new trusted advisor API

### ISSUE THREAD

**Issue by alFReD-NSH** [awslabs/cid-framework#190]
The new trusted advisor API allows to fetch the recommendations globally from management account which simplifies the data collection.

**Comment by iakov-aws** [comment]
Hello @alFReD-NSH 

It would be great, but as of today the api [trustedadvisor.list_organization_recommendations](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/trustedadvisor/client/list_organization_recommendations.html) support only supports prioritized recommendations aka [TA Priority](https://aws.amazon.com/premiumsupport/technology/trusted-advisor-priority/). 

<img width="846" alt="image" src="https://github.com/user-attachments/assets/8f1d9c01-6e37-4c46-8673-fdb43aceb684">


Please follow this issue: https://github.com/awslabs/cid-framework/issues/175
