### ISSUE TITLE
OUs under roots excluded from RLS scan

### ISSUE THREAD

**Issue by jborhen-tc** [awslabs/cid-framework#206]
- A reproducible test case or series of steps
  - Create 20 OUs under root
  - Run CIDRLS Lambda
  - Only last 5 OUs are scanned for cid_users and cid_groups tags
- The version of our code being used
  - Current
- Any modifications you've made relevant to the bug
  - Extended the OUs results  with the previous results
- Anything unusual about your environment or deployment
  - None 

I believe the issue lies in the line below
https://github.com/awslabs/cid-framework/blob/b6c156423b19976824b6d0595905a00023b6a8b3/rls/deploy/create_rls.py#L77

**Comment by iakov-aws** [comment]
@vmindru Any thought?

**Comment by vmindru** [comment]
Checking

**Comment by iakov-aws** [comment]
@vmindru any update?

**Comment by iakov-aws** [comment]
@vmindru any update?

**Comment by vmindru** [comment]
@jborhen-tc  can you please test agai using this code https://raw.githubusercontent.com/awslabs/cid-framework/refs/heads/large_ou_crawler_fix/rls/deploy/create_rls.py

**Comment by jborhen-tc** [comment]
Hey @vmindru , unfortunately I am not at liberty of changing our current solution especially when we have already implemented a fix. 
Essentially, I have altered the function below to extend `list_ous_result ` with the previous iteration's `list_ous_result ` ous ids(see comments).
```python
def get_children_ou(ou, org_client):
    NextToken = True
    children_ou = []
    while NextToken:
        if type(NextToken) is str:
            # Save previous list_ous_result OUs IDs in a temporary variable
            list_ous_result = org_client.list_organizational_units_for_parent(ParentId=ou, MaxResults=20, NextToken=NextToken)
            # Extend list_ous_result  with the OUs IDs in the temporary variable
        else:
            list_ous_result = org_client.list_organizational_units_for_parent(ParentId=ou, MaxResults=20)
        if 'NextToken' in list_ous_result:
            NextToken = list_ous_result['NextToken']
        else:
            NextToken = False
        ous = list_ous_result['OrganizationalUnits']
        for child_ou in ous:
            children_ou.append(child_ou['Id'])
    return children_ou
```

**Comment by vmindru** [comment]
Hi @jborhen-tc  thanks, this is  good enough,  the fix in   https://raw.githubusercontent.com/awslabs/cid-framework/refs/heads/large_ou_crawler_fix/rls/deploy/create_rls.py is litterly the same you did here.

**Comment by vmindru** [comment]
again thanks a lot for reporting and for further comments, have a good one.

**Comment by jborhen-tc** [comment]
I appreciate the support, I believe this can be closed now.

**Comment by vmindru** [comment]
@jborhen-tc  just to clear,  please do not use yet the code in the patch mentioned, your fix is good enough. The  patch i suggested has other changes that where not fully tested yet. Have a good day.

**Comment by jborhen-tc** [comment]
@vmindru Sure thing, I will refrain from that. Have a great day!
